### ISSUE TITLE
Enhancement: LightGraphs integration?

### ISSUE THREAD

**Issue by sbromberger** [chkwon/RobustShortestPath.jl#1]
Hi,

You might find that `LightGraphs.jl`'s optimized shortest paths algorithms perform better than Graphs for simple graphs (with no metadata like edge labels/names, etc.). I'd be happy to help if you're interested in testing it.

**Comment by chkwon** [comment]
Thanks for brining LightGraphs.jl to my attention. I am very much interested in. Let me come back when I have time for it. Perhaps in a few weeks.

**Comment by chkwon** [comment]
@sbromberger I have updated my package using `LightGraphs.jl`. Thanks.
